### ISSUE TITLE
Add OpenSimplex2 Noise and perhaps use it in the examples instead of Perlin

### ISSUE THREAD

**Issue by mystise** [AnotherCraft/ac-worldgen#3]
Perlin has many issues (expanded upon here: https://noiseposti.ng/posts/2022-01-16-The-Perlin-Problem-Moving-Past-Square-Noise.html ) and OpenSimplex2 is CC0 public domain: https://github.com/KdotJPG/OpenSimplex2

This seems like a neat project and it'd be cool to have noise that's not heavily cube-aligned available by default.

As an alternative to porting OpenSimplex2 yourself, and as a bonus getting a whole bunch of other noise generators at the same time, integrate FastNoise Lite (MIT) https://github.com/Auburn/FastNoiseLite as a generator backend

**Comment by CZDanol** [comment]
Here you go, boss! Used FastNoise2 instead as it seemed to have more fitting API for me and faster.

Also tried comparing their & mine Perlin 2D/3D implementations and mine seems faster, heh. I have an advantage knowing that the nodes will be always aligned though.
